### ISSUE TITLE
How to use it?)

### ISSUE THREAD

**Issue by justscribe** [mono/Mono.Nat#14]
Hi,

I'm using MonoTorrent and want to clients can seed even if port not forwarded by it's router.
I've tried to use this utility, but with no luck, I still can't connect with the specified port.
Code example:
```
private async void DeviceFoundAsync(object sender, DeviceEventArgs e) {
            await _locker.WaitAsync();
            try {
                INatDevice device = e.Device;
                Mapping mapping = new Mapping(Protocol.Tcp, Core.TorrentClient.Port, Core.TorrentClient.Port);
                await device.CreatePortMapAsync(mapping);
                try {
                    Mapping m = await device.GetSpecificMappingAsync(Protocol.Tcp, Core.TorrentClient.Port);
                } catch {                    
                }
            } catch (Exception exc) {
                
            } finally {
                _locker.Release();
            }
        }
```
Is this is correct?

**Comment by alanmcgovern** [comment]
Yup!

There's no guarantee the users will have functional upnp or nat-pmp. It is possible for CreatePortMapAsync to throw an exception, so it should be wrapped in a try/catch too.

If you can add logging to see if any devices were discovered, and also if the port map was successful, that may help.

**Comment by justscribe** [comment]
Can it be somehow checked, if user can or can't use that upnp or nat-pmp functionality?

**Comment by alanmcgovern** [comment]
NAT Is not necessarily the same things as UPnP Port Forwarding or NAT-PMP. This is what my router has.

<img width="560" alt="Screenshot 2019-12-05 at 10 45 53" src="https://user-images.githubusercontent.com/264396/70228541-6b196080-174c-11ea-8af5-fcea1cf47062.png">

My router also turns off 'NAT' when you enter 'Modem Mode'
<img width="737" alt="Screenshot 2019-12-05 at 10 46 38" src="https://user-images.githubusercontent.com/264396/70228674-a582fd80-174c-11ea-8b8f-3e282082acf0.png">

It's possible that your 'NAT' selector is related to that, rather than related to  UPnP.

If you call `NatUtility. StartDiscovery` and no devices are found, then that's the best indicator there are no compatible devices. If other upnp/nat-pmp software *can* find a compatible device the there is a way to help diagnose the issue: https://smuxi.im/wiki/mono-nat/Debugging_the_reason_why_your_router_cannot_be_found

You could try enable that logging anyway and see what shows up in the logs.

**Comment by justscribe** [comment]
That is the output.
```
UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Thu, 05 Dec 2019 10:53:29 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Linux/3.14.43 UPnP/1.0 WPS/20
ST: upnp:rootdevice
USN: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0::upnp:rootdevice


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Thu, 05 Dec 2019 10:53:29 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Linux/3.14.43 UPnP/1.0 WPS/20
ST: upnp:rootdevice
USN: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0::upnp:rootdevice


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Thu, 05 Dec 2019 10:53:29 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Linux/3.14.43 UPnP/1.0 WPS/20
ST: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0
USN: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Thu, 05 Dec 2019 10:53:29 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Linux/3.14.43 UPnP/1.0 WPS/20
ST: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0
USN: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Thu, 05 Dec 2019 10:53:29 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Linux/3.14.43 UPnP/1.0 WPS/20
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0::urn:schemas-wifialliance-org:device:WFADevice:1


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Thu, 05 Dec 2019 10:53:29 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Linux/3.14.43 UPnP/1.0 WPS/20
ST: urn:schemas-wifialliance-org:device:WFADevice:1
USN: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0::urn:schemas-wifialliance-org:device:WFADevice:1


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Thu, 05 Dec 2019 10:53:29 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Linux/3.14.43 UPnP/1.0 WPS/20
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0::urn:schemas-wifialliance-org:service:WFAWLANConfig:1


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1801
DATE: Thu, 05 Dec 2019 10:53:29 GMT
EXT:
LOCATION: http://192.168.1.1:49152/wps_device.xml
SERVER: Linux/3.14.43 UPnP/1.0 WPS/20
ST: urn:schemas-wifialliance-org:service:WFAWLANConfig:1
USN: uuid:2d87b6e6-11f7-40db-8cb7-6038e08fc2c0::urn:schemas-wifialliance-org:service:WFAWLANConfig:1


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1810
DATE: Thu, 05 Dec 2019 10:53:29 GMT
ST: uuid:4d696e69-444c-164e-9d41-6038e08fc2c0
USN: uuid:4d696e69-444c-164e-9d41-6038e08fc2c0
EXT:
SERVER: 3.5.0-45-generic DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.2.0
LOCATION: http://192.168.1.1:9999/rootDesc.xml
Content-Length: 0


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1810
DATE: Thu, 05 Dec 2019 10:53:29 GMT
ST: upnp:rootdevice
USN: uuid:4d696e69-444c-164e-9d41-6038e08fc2c0::upnp:rootdevice
EXT:
SERVER: 3.5.0-45-generic DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.2.0
LOCATION: http://192.168.1.1:9999/rootDesc.xml
Content-Length: 0


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1810
DATE: Thu, 05 Dec 2019 10:53:29 GMT
ST: urn:schemas-upnp-org:device:MediaServer:1
USN: uuid:4d696e69-444c-164e-9d41-6038e08fc2c0::urn:schemas-upnp-org:device:MediaServer:1
EXT:
SERVER: 3.5.0-45-generic DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.2.0
LOCATION: http://192.168.1.1:9999/rootDesc.xml
Content-Length: 0


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1810
DATE: Thu, 05 Dec 2019 10:53:30 GMT
ST: urn:schemas-upnp-org:service:ContentDirectory:1
USN: uuid:4d696e69-444c-164e-9d41-6038e08fc2c0::urn:schemas-upnp-org:service:ContentDirectory:1
EXT:
SERVER: 3.5.0-45-generic DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.2.0
LOCATION: http://192.168.1.1:9999/rootDesc.xml
Content-Length: 0


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1810
DATE: Thu, 05 Dec 2019 10:53:30 GMT
ST: urn:schemas-upnp-org:service:ConnectionManager:1
USN: uuid:4d696e69-444c-164e-9d41-6038e08fc2c0::urn:schemas-upnp-org:service:ConnectionManager:1
EXT:
SERVER: 3.5.0-45-generic DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.2.0
LOCATION: http://192.168.1.1:9999/rootDesc.xml
Content-Length: 0


UPnP Response: HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1810
DATE: Thu, 05 Dec 2019 10:53:31 GMT
ST: urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1
USN: uuid:4d696e69-444c-164e-9d41-6038e08fc2c0::urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1
EXT:
SERVER: 3.5.0-45-generic DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.2.0
LOCATION: http://192.168.1.1:9999/rootDesc.xml
Content-Length: 0
```

**Comment by justscribe** [comment]
Found...
![image](https://user-images.githubusercontent.com/8200485/70229596-34991100-175f-11ea-912a-533b55329813.png)

**Comment by justscribe** [comment]
Another problem)
```
05.12.2019 13:02:33> Error ActionFailed: PAL_UPNP_SOAP_E_ACTION_FAILED | Mono.Nat.MappingException: Error ActionFailed: PAL_UPNP_SOAP_E_ACTION_FAILED
   at Mono.Nat.Upnp.ResponseMessage.Decode(UpnpNatDevice device, String message)
   at Mono.Nat.Upnp.UpnpNatDevice.<DecodeMessageFromResponse>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.Nat.Upnp.UpnpNatDevice.<SendMessageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mono.Nat.Upnp.UpnpNatDevice.<CreatePortMapAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SVitLAB.Net.NatWorker.<DeviceFoundAsync>d__6.MoveNext() in NatWorker.cs:line 59 | DeviceFoundAsync
```

**Comment by alanmcgovern** [comment]
The verbose logs may help diagnose this. UPnP is based on XML, and many manufacturers generate it differently/incorrectly and many routers have unusual quirks.

NAT-PMP is a binary format and, generally speaking, always works :(

**Comment by alanmcgovern** [comment]
In addition to that, can you try setting the `Lifetime` on the `Mapping` object to something like 7200 (2 hours)? Some routers fail when you pass a non-zero value, some fail when you pass a value of zero. Zero is supposed to mean 'indefinite' according to the spec.

**Comment by justscribe** [comment]
1. There is no Verbose property=)
2. With 7200 or 0 Lifetime error is the same.
3. Issue resolved by setting "Allow users to configure" to enabled in router.
I think that may increase amount of seeds. Many depends from router default config.
Thank you for help.

**Comment by alanmcgovern** [comment]
Ah awesome! Glad you got your router working :) 

It would definitely be useful to ship upnp/nat-pmp support in some form, and if possible prompt users to manually enable upnp (or manually forward ports) if a client is unreachable.

**Comment by justscribe** [comment]
But if user already reachable, and we'll enable forwarding, can that bring some issues?

**Comment by alanmcgovern** [comment]
No, it shouldn't. If a manual port mapping was created by the user then the automatic upnp one will be ignored, or the CreatePortMap call will fail with an exception. 

This could always be made an option the user can choose to disable. However I'd have it enabled by default
